name = "markdowner"
main = "src/index.ts"
compatibility_date = "2023-09-04"
compatibility_flags = [ "nodejs_compat"]


# Browser Rendering API binding
browser = { binding = "MYBROWSER" }

[observability.logs]
enabled = true

[[durable_objects.bindings]]
name = "BROWSER"
class_name = "Browser"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["Browser"] # Array of new classes for free plan

[[kv_namespaces]]
binding= "MD_CACHE"
id = "b2659b2218574f99ab8f9bd49ca8fc67"
preview_id = "c87a4ce9271943cca859415b6898ea13"

[[unsafe.bindings]]
name = "RATELIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 10, period = 60 } # 10 requests per 60 seconds

[ai]
binding = "AI"
